// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_fetch_breaking_news_html
std::string cpp_fetch_breaking_news_html(Rcpp::CharacterVector subjects);
RcppExport SEXP _newsfeed_cpp_fetch_breaking_news_html(SEXP subjectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type subjects(subjectsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fetch_breaking_news_html(subjects));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_newsfeed_cpp_fetch_breaking_news_html", (DL_FUNC) &_newsfeed_cpp_fetch_breaking_news_html, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_newsfeed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
