# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_fetch_breaking_news_html <- function() {
    .Call(`_newsfeed_cpp_fetch_breaking_news_html`)
}

